(function(n){var g=Object.prototype,q=g.hasOwnProperty,e=function(){for(var a="Object Array Boolean Date Function Number Null RegExp String Undefined".split(" "),c=g.toString,h={},b=a[0].toLowerCase(),l,m=a.length;m--;)l=a[m],h["["+b+" "+l+"]"]=l.toLowerCase();return function(a,l){var m=typeof a;if(m===b||"function"===m)m=null===a?"null":h[c.call(a)]||b;return l?l===m:m}}(),p=Array.prototype,r=function(){var a=p.isArray;e(a,"function")||(a=p.isArray=function(){return e(this,"array")});return function(c){return a.call(c)}}(),
d=function(a,c,h){a=r(a)?a:a.split(".");c=c||n;var b,l;h=!1!==h;for(var m=0;m<a.length;m+=1){b=a[m];l=c[b];if(!e(l,"object"))if(h)c[b]=l={};else break;c=l}return c},k=function(){var a,c,h,b,l,m,u;e(arguments[0],"boolean")&&(h=p.shift.apply(arguments));if(!(2>arguments.length)){a=p.shift.apply(arguments);c=e(a);"object"!=c&&"function"!=c&&"array"!=c&&(a={});c=arguments;for(var s=0,F=c.length;s<F;s+=1)if(e(b=c[s],"object")||r(b))for(var f in b)if(q.call(b,f)&&b[f]!==a){l=a[f];m=b[f];var d;if(!(d=u=
r(m))){if(d=e(m,"object")){var y=(d=m)&&e(d,"object")&&!(d.nodeType||d!=d.window),y=void 0;try{!d.constructor||q.call(d,"constructor")||q.call(d.constructor.prototype,"isPrototypeOf")}catch(A){}for(y in d);d=y=e(y,"undefined")||q.call(d,y)}d=d&&h}d?(l=u?r(l)?l:[]:e(l,"object")?l:{},a[f]=k(!0,l,m)):e(m,"undefined")||(a[f]=m)}return a}},t=function(){var a=[],c,h,b,l,m,d,s;e(arguments[0],"boolean")&&(l=p.shift.call(arguments));for(var f=0;f<arguments.length;f++)e(b=arguments[f],"object")&&a.push(b);
m=a.shift();if(a.length)for(f=0;f<a.length;f++){b=a[f];for(var k in b)q.call(b,k)&&(c=b[k])!=(h=m[k])&&(d=e(c),s=e(h),m[k]=d==s=="object"&&l?t(h,c):"undefined"!=s?[].concat(h,c):c)}return m},D=function(){e(p.indexOf,"function")||(p.indexOf=function(a){var c,h;if(null==this)throw new TypeError;c=Object(this);h=c.length>>>0;for(var b=0;b<h;b++)if(b in c&&c[b]===a)return b;return-1});return function(a,c){return p.indexOf.call(c,a)}}();(function(){var a=Function.prototype;e(a.bind,"function")||(a.bind=

function(a){var h=this,b;if(!e(h,"function"))throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");b=p.slice.call(arguments,1);return function(){return h.apply(a,b.concat(p.slice.call(arguments)))}})})();e(Object.create,"function")||function(){function a(){}Object.create=function(c){if(1!=arguments.length)throw Error("Current Object.create implementation only accepts one parameter.");a.prototype=c;return new a}}();Object.keys||(Object.keys=function(){var a=!{toString:null}.propertyIsEnumerable("toString"),
c="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" ");return function(h){if("object"!==typeof h&&("function"!==typeof h||null===h))throw new TypeError("Object.keys called on non-object");var b=[],l;for(l in h)q.call(h,l)&&b.push(l);a&&c.forEach(function(a){q.call(h,a)&&b.push(a)});return b}}());var w=function(){return function(a){var c=a.onclick,h=a._options,b;if(null!=c){try{b=c()}catch(l){}a.removeAttribute("onclick");a.onclick=null;a._options=
b}else null!=h&&(b=h);return b}}(),f=function(){function a(a){a||(a=n.location.hostname.split(".").slice(0,-2).join("."));c=c||{};return d(a,c)}var c;return{get:function(c,b){return a(b)[c]},set:function(c,b,l,m){b=a(b);var d=b[c];!d||m?d=b[c]=k(!0,{},l):k(!0,d,l);return d}}}(),v=d("ru.mail.cntnt_prjcts");k(d("ru.mail"),{cpf:v});k(d("Basic",v),{Extend:k,Merge:t,getOptions:w,moduleOpts:f,typeOf:e,getConstructor:function(a){var c=function(){var a=this,b;a instanceof c||(a=new c(c));arguments[0]!==c&&
(b=a._Init.apply(a,arguments),e(b,"object")?a=b:a._Init=null);return a};e(a,"object")&&(c.prototype=a,c.prototype.constructor=c);return c},getByPath:function(a,c){var h=r(a)?a:a.split("."),b=d(h.slice(0,h.length-1),c,!1),l=null;null===b||e(b,"undefined")||(l=b[h.pop()]);return l}});k(d("Types.Array",v),{indexOf:D,isArray:r});n.getNameSpace=d})(window);

(function(n,g,q){var e=n(g),p=n(g.document);q.Basic.Extend(g.getNameSpace("Comp.jQuery",q),function(){var g={Elems:{jBody:null,jDoc:p,jWindow:e}};n(function(){g.Elems.jBody=n("body")});return g}())})(jQuery,window,getNameSpace("ru.mail.cpf"));

(function(n,g,q){g=g.getNameSpace;var e=q.Basic,p=e.typeOf,r=Array.prototype,d=g("Comp.jQuery",q);e.Extend(d,function(){function k(d,e,f){var g=/^in/i,a,c,h;f=f||{};for(var b in d)d.hasOwnProperty(b)&&(a=d[b],c=p(a),"string"==c&&a.length?(c="j"+b.substr(0,1).toUpperCase()+b.substr(1),f[c]=(h=e.find(a)).length?h:e.is(a)?e:null):"object"==c&&(c="j"+b.replace(g,""),c=f[c],c instanceof n&&c.length&&k(a,c,f)));return f}var e=function(){var e=d.Elems.jWindow,k=["scroll","resize"],f,g=function(){var a=q.Comp.Tools.Callbacks,
c=arguments,c=p(c[0],"boolean")?r.shift.apply(c):!0;if(p(a,"function")&&(c&&p(f,"undefined")&&(f=a({Types:k}),e.bind(k.join(" "),function(a){a=a.type;f.fire(a,[{top:e.scrollTop(),left:e.scrollLeft()},{height:e.height(),width:e.width()},a])})),!p(f,"undefined")))for(var d=0;d<k.length;d++)if(a=arguments[d],p(a,"undefined")&&(a=arguments[d-1]),p(a,"function"))f[c?"add":"remove"](k[d],a)};return{attach:g,detach:function(){r.unshift.call(arguments,!1);g.apply(null,arguments)}}}();return{Tools:{getElements:k,
winHndlrs:e,toggleElemsVal:function(d,e,f){e=e||{};var k,a,c,h,b;for(b in d)if(d.hasOwnProperty(b)&&(k=d[b])&&k.length)if(a=k.is("input, select, textarea")?"val":"html",h=f&&b in f?f[b]:b,c=e[h])k[a](c);else e[h]=k[a]();return e}}}}())})(jQuery,window,getNameSpace("ru.mail.cpf"));

(function(n,g){var q=n.getNameSpace,e=q("Basic",g),p=e.typeOf;e.Extend(q("Types.String",g),function(){var e=String.prototype;return{getPlural:function(d,e){d%=100;if(10<d&&20>d)return e[2];switch(d%10){case 1:return e[0];case 2:case 3:case 4:return e[1];default:return e[2]}},trim:function(){var d=e.trim;p(d,"function")||(e.trim=function(){return this.replace(/^\s+|\s+$/g,"")});return function(d){return e.toString.call(d).trim()}}(),getNearest:function(d,e,g){var q,n,f=-1;g=g||0;for(var r=0;r<e.length;r++)p(q=
e[r],"string")&&-1<(n=d.indexOf(q,g))&&(f=Math[0>f?"max":"min"](n,f));return f},cutBySpace:function(d,e){var g;if(d.length<=e)return d;g=d.substr(0,e);" "!=d.charAt(e)&&(g=g.substr(0,g.lastIndexOf(" ")));return g},regExp:{Url:/^(?:http(?:s)?:\/\/)?(?:(?:[a-z0-9\-]+\.)+[a-z]{2,4})?\/?(?:[a-z0-9\-_]+(?:\/|(?:\.[a-z0-9]+)))*(?:\?.*)?$/i}}}())})(window,window.getNameSpace("ru.mail.cpf"));

(function(n,p,y){function z(a,b,c,d){b&&(d=[b,"[",a?"":d,"]"].join(""));switch(g(c)){case "array":case "object":c=q(c,d);break;default:a=[encodeURIComponent(d)],null!=c&&0!==c.length&&a.push("?"!==c?encodeURIComponent(c):c),c=a.join("=")}return c}function r(a,b,c,d){var e=null===a;return c.concat(z(e,b,e?d:a[d],e?null:d))}function q(a,b){var c=[];switch(g(a)){case "array":c=a.reduce(r.bind(null,null,b),c);break;case "object":c=Object.keys(a).reduce(r.bind(null,a,b),c)}return c}function s(a){var b=
{path:"",query:"",hash:""},c,d;if(!a)return b;a=a.replace(/\+/g," ").trim();0<=a.indexOf("?")?(c=a.split("?"),b.path=c[0],a=c[1]):A.test((c=a.split("#"))[0])||t.test(c[0])?(b.path=c[0]||"",b.hash=c[1]||"",d=!0):b.query=a;d||(c=a.split("#"),b.query=c[0]||"",b.hash=c[1]||"");return b}function u(a,b,c){var d=s(b);d.query=v(d.query,!1)||{};b=d.path;var e=d.hash;a=B(!0,{},c?{}:d.query,a);a=q(a).join("&").replace(/%20/g,"+");return b+(b&&a?"?":"")+a+(e?"#"+e:"")}function v(a,b){var c={};if(g(b,"undefined")||
b)a=s(a).query;if(!a)return null;a.split("&").forEach(function(a){var b=a.split("="),h=c,k,l,f;g(b[1],"undefined")&&(b=(b=a.match(C))?b.slice(1):[a,null]);a=decodeURIComponent(b[0]).split("][");a=a.shift().split("[").concat(a);a[a.length-1]=a[a.length-1].replace("]","");b=(b=decodeURIComponent(b[1]))&&!isNaN(b)?+b:w[b]!==y?w[b]:b;k=a.length;if(1<k)for(f=0;f<k;f++)l=""===a[f]?h.length:a[f],h=f<k-1?h[l]=h[l]||(a[f+1]&&isNaN(a[f+1])?{}:[]):h[l]=b;else c[a[0]]=b});return c}var x=n.getNameSpace,m=x("Basic",
p),g=m.typeOf,B=m.Extend,A=/^\/?([^=&#\/]+\/)+[^=&#\/]*$/,t=/^(http(s?):)?\/\/[^\/]+/i,C=/([a-z-_]+)([0-9,]+)/i,w={"true":!0,"false":!1,"null":null,undefined:null,"":null};String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});m.Extend(x("Types.String.Url",p),{getAbs:function(a){var b=n.location;if(g(a,"string"))return a=a.trim(),t.test(a)||(a=b.protocol+"//"+b.hostname+("/"==a.charAt(0)?"":b.pathname)+a),a},addParam:function(a,b,c,d){var e={};e[b]=c;return u(e,
a,d)},addParams:u,getParams:v})})(this,this.ru.mail.cpf);

(function(n,g,q){var e=q.Basic,p=g.getNameSpace,r=e.getConstructor(function(){var d=p("Comp.jQuery.Tools",q).getElements,k=e.typeOf,t=e.Extend,D=q.Types.String,w=D.Url,f={my:{baseUrl:"http://connect.mail.ru/",url:"share",count:"share_count?callback=1",countUseCallback:!0,getCount:function(a,c){var b;return a&&(b=a[c])&&b.shares||0},sizes:[550,340],params:{url:"share_url",title:"title",description:"description",image:"imageurl"},countParams:{url:"url_list",callback:"func"}},ok:{baseUrl:"http://www.odnoklassniki.ru/",
url:"dk/?st.cmd=addShare",count:"dk/?st.cmd=extLike",countUseCallback:!1,getCount:null,sizes:[550,320],params:{url:"st._surl"},countParams:{url:"ref",id:"uid",callback:"callback"}},fb:{baseUrl:null,url:"http://www.facebook.com/sharer.php",count:"http://api.facebook.com/restserver.php?method=links.getStats&format=json",countUseCallback:!0,getCount:function(a){var c,b=0;a&&(c=a[0])&&(b=c.share_count||b);return b},sizes:[660,370],params:{url:"p[url]",title:"p[title]",description:"p[summary]",image:"p[images][0]",
_url:"u"},countParams:{url:"urls",callback:"callback"},addParams:{s:100}},vk:{baseUrl:"http://vk.com/",url:"share.php",count:"share.php?act=count&format=json",countUseCallback:!1,getCount:null,sizes:[660,390],params:{url:"url",title:"title",description:"description",image:"image"},countParams:{url:"url",id:"index",callback:"callback"}},tw:{baseUrl:null,url:"https://twitter.com/share",count:"https://cdn.api.twitter.com/1/urls/count.json",countUseCallback:!0,getCount:function(a){return a.count},sizes:[550,
300],params:{charsLimit:114,url:"url",via:"via"},countParams:{url:"url",callback:"callback"}}},v=/cl(?:n|b)/i,a={cssSels:{Btns:".js-shares_btn",Cnts:".js-shares_cnt"},showCnt:!0,getCntOnInit:!0,typeAttr:"data-share",urlTypeParam:null,url2Share:null,Counters:null,addParams:null,shareParams:{Title:null,Description:null,Image:null},prepareParams:null,ignoreMetaParams:-1<navigator.userAgent.toLowerCase().indexOf("msie")},c={title:"Title",description:"Description",image:"Image"},h={title:100,descr:500},
b=["url","image","title","description"],l=function(){var a={};return function(c,b,d){b=k(b,"undefined")?this.url2Share:b;var e=c+b,f=a[e];if(!d&&f)return f;f=w.getAbs(b);b=this.Opts.urlTypeParam;if(!f||!c)return null;null!==b&&(f=w.addParam(f,b?b:c,b?c:null));e&&(a[e]=f);return f}}(),m=function(a,b){var c;if(b){if("object"==(c=k(b)))return b[a];if("string"==c)return b}},u=function(){var a={},b,c=function(a,c,d){var e,f;b&&(e=b[a])&&k(f=e[c],"function")&&(e[c]=null,f.call(null,d))},d=function(){g.ODKL=
t(g.ODKL,{updateCount:function(a,b){c.apply(null,["ok",a,b])}});g.VK=t(g.VK,{Share:{count:function(a,b){c.apply(null,["vk",a,b])}}})},e=function(b,c){var d=a[b];c=l.apply(this,[b,c]);return d&&d[c]},h=function(a){var b=this.Elems.byType[a].Count,c;b&&b.length&&(c=isNaN(c=e.call(this,a))?0:c,b.text(c),b.toggle(0<c))},K=function(b,c,d){var e=a[c];isNaN(b*=1)||(k(e,"object")||(a[c]=e={}),e[d]=b,d===l.call(this,c)&&h.call(this,c))},O=function(a,c){var d;k(b,"object")||(d=g.getNameSpace("Instances",q),
d.oShareCallbacks?b=d.oShareCallbacks:d.oShareCallbacks=b={});(d=b[a])instanceof Array||(d=b[a]=[]);return d.push(c)-1},m=function(a){var b=this,c=f[a],e=c.countParams,h=c.countUseCallback,g=l.call(this,a),k={},m;k[e.url]=g;h||(k[e.id]=O.apply(this,[a,function(c){K.apply(b,[c,a,g])}]));e.url&&(k[e.callback]="?");e=w.addParams(k,((m=c.baseUrl)?m:"")+c.count);d();n.getJSON(e,h?function(d){d=c.getCount(d,g);K.apply(b,[d,a,g])}:null)};return{getTypeCount:function(a,b){isNaN(e.call(this,a))||!0===b?m.call(this,
a):h.call(this,a)},initCbcks:d}}().getTypeCount,s=function(){for(var a=0,b=this.Types;a<b.length;a++)u.call(this,b[a])},F=function(){var a=this.Elems,b=this.Opts,c=b.typeAttr,d=a.byType={},e=this.Types=[];a.jBtns.each(function(f){var h=n(this),g=h.attr(c),k=d[g]={};g&&(e.push(g),k.Btn=h.removeAttr(c).data("shareType",g),b.showCnt&&(k.Count=a.jCnts.eq(f)))})},J=function(){function a(){var b={};n("meta",document.head).each(function(){var a=this.getAttribute("property")||this.getAttribute("name"),c;
a&&("description"===a||(c=a.split(":"))&&2===c.length&&"og"===c.shift())&&(b[c&&c.shift()||a]=this.getAttribute("content"))});return b}function d(a,b){var c={};c[a]=b;return c}var e=function(a){var b=this,c=this._Timers.ppCheckTimer;c&&(clearTimeout(c),this.ppCheckTimer=null,u.call(this,a,!0));this._Timers.ppCheckTimer=setTimeout(function(){var c;b._Timers.ppCheckTimer=null;b.curWin.closed?(u.call(b,a,!0),c=b&&b.counts&&b.counts[a],n(g).trigger("share_window_closed",a,c)):e.call(b,a)},500)},p=function(){var a=
{};return function(b){var c=a[b],d,e;if(c)return c;d=f[b];c=this.Opts.Counters;d=(d.baseUrl||"")+d.url;c&&(e=m(b,c))&&(e="http://r.mail.ru/"+(k(e,"string")&&v.test(e)?"":"cln")+e);return a[b]=c=e?e+"/"+d.substr(d.indexOf("://")+3):d}}(),q=function(a){for(var b,c=[],d,e,f=0;f<a.length;f++)b=a[f],d=f?"height":"width",e=f?"top":"left",c.push(d+"="+b,e+"="+Math.max(0,Math.round(screen[d]/2-b/2)));return c.join(",")};return function(n){var r;var s=this.Opts.addParams,v=l.call(this,n),C=f[n],u=C.params,
F=C.addParams,C=p.call(this,n);if(v){var I=t({},this._shareParams),G=this.Opts,B=I.via,L=G.prepareParams,E=[],z,x,H,M;k(L,"function")&&L.call(this,I,n);!0!==G.ignoreMetaParams&&(z=a());if("tw"!=n)for(G=0;G<b.length;G++)B=b[G],c.hasOwnProperty(B)&&(x=I[c[B]]||z&&z[B])&&((H=h[B])&&x.length>H&&(H-=3,x=x.substr(0,H)+(" "!=x.charAt(H)?"...":"")),(M=u[B])&&E.push(d(M,x)));else z=I.Title||document.title,z=z.replace(/\"/g,""),x=u.charsLimit,B&&(E.push(d("via",B)),x-=11+B.length),z.length>x&&(z=D.cutBySpace(z,
x-3)+"..."),E.push(d("text",z));u=0===E.length&&u._url||u.url;E.unshift(d(u,v));F&&(r=t({},F));s&&(r=t(r||{},m(n,s)));for(s=0;s<E.length;s++)C=w.addParams(E[s],C);r&&(C=w.addParams(r,C));r=C}else r=null;s=f[n];if(r&&s){if(v=this.curWin)try{v.close()}catch(J){}this.curWin=g.open(r,"share",q(s.sizes)+",personalbar=0,toolbar=0,scrollbars=1,resizable=1");this.Opts.showCnt&&e.call(this,n)}}}(),N=function(){var a=this;this.Elems.jBtns.bind("click",function(b){b.preventDefault();J.call(a,n(this).data("shareType"))})};
return{_Init:function(b,c){var e;e=b.data("shareBtnsObj");if(e instanceof r)return e;b.data("shareBtnsObj",this);this.Opts=e=t(!0,{},a,c);this.url2Share=e.url2Share||g.location.href;this._shareParams=e.shareParams;this.Elems=d(e.cssSels,b,{jCont:b});this._Timers={};F.apply(this);this.Types.length&&(N.apply(this),e.showCnt&&!0===e.getCntOnInit&&s.apply(this))},setUrl2Share:function(a,b,c){a&&k(a,"string")&&(this.url2Share=a,b&&(k(c,"undefined")||c?this._shareParams=t(!0,{},b):this._shareParams=t(!0,
this._shareParams,b)),this.Opts.showCnt&&(this.Elems.jCnts.hide(),s.apply(this)))}}}());n.fn.initShareBtns=function(d){return this.each(function(){r(n(this),d)})};p("Comp.jQuery.Modules",q).shareButtons=r})(jQuery,this,this.ru.mail.cpf);